blank_issues_enabled: true
contact_links:
  - name: Join our Discord community.
    url: https://caffeinemc.net/discord
    about: Get installation help and technical support with all of our mods.
    # Copied from https://github.com/CaffeineMC/sodium-fabric#community
